# Generated by Django 5.1.2 on 2024-10-21 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_num', models.IntegerField(verbose_name='Card number')),
                ('deadline', models.CharField(max_length=10, verbose_name='Deadline')),
                ('balance', models.IntegerField(verbose_name='Balance')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Datetime')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('card_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.card')),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cards.category')),
            ],
        ),
    ]
