# Generated by Django 5.1.2 on 2024-10-21 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='bank_name',
            field=models.CharField(max_length=200, null=True, verbose_name='Bank name'),
        ),
    ]
