# Generated by Django 5.1.2 on 2024-10-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_card_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_num',
            field=models.BigIntegerField(verbose_name='Card number'),
        ),
    ]
