# Generated by Django 5.1.2 on 2024-10-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_card_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.BigIntegerField(verbose_name='Balance'),
        ),
    ]
