# Generated by Django 5.1.2 on 2024-10-21 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_card_phone_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.BigIntegerField(null=True, verbose_name='Balance'),
        ),
    ]
