# Generated by Django 5.1.2 on 2024-10-23 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_card_balance_alter_card_bank_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='card_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='value',
        ),
        migrations.AddField(
            model_name='transaction',
            name='from_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='cards.card'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='to_card',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_card', to='cards.card'),
        ),
    ]
